services:
  - type: web
    name: ai-lawyer
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false   # Add value in Render dashboard → Environment → Add Environment Variable
      - key: COHERE_API_KEY
        sync: false   # Add value in Render dashboard → Environment → Add Environment Variable
